export const menuIcon = document.querySelector(".menuImg");
export const sideBar = document.querySelector(".sidebar");
export const mainContent = document.querySelector(".mainContent");
export const list = document.querySelectorAll("#main-list > li");
export const check = document.querySelector(".checkImg");
// export const projectList = document.querySelector(".project-ul");
export const plus = document.querySelector('.plus')
// export const projectList2 = document.querySelector(".project-ul")
export const secondList = document.querySelectorAll(".list")
export const projectTitlePara = document.querySelector('.Project-Title')
export const projectBtn = document.querySelector('.add-Project')
export const projectInput = document.querySelector('#projectName')
export const projectForm = document.querySelector('.project-form')
export const projectUl = document.querySelector('.project-ul')
export const addProjectBtn = document.querySelector('.add')
export const updateProjectBtn = document.querySelector('.update')
export const cancleProjectBtn = document.querySelector('.cancle')
export const projectTitle = document.querySelector('.Project-Title h2')
export const projectRename = document.querySelector('.select')
export const addTaskButton = document.querySelector('.addTaskButton')
export const taskForm = document.querySelector('.task-form')
export const taskCancleButton = document.querySelector('.task-cancle-btn')
export const taskAddbutton = document.querySelector('.task-add-btn')
export const taskNameInput = document.querySelector('#name-input')
export const taskDetailInput = document.querySelector('#details-input')
export const taskDateInput = document.querySelector('#date-input')
export const taskListSect = document.querySelector('.task-list')
export const taskMainDiv = document.querySelector('.task-main-div')
export const statusInput = document.querySelector('.status')